micronaut:
  application:
    name: keyManagerGrpc

grpc:
  server:
    port: ${GRPC_SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5435/km_grpc_pix`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    dialect: ${DB_DIALECT:POSTGRES}
jpa.default.properties.hibernate.hbm2ddl.auto: ${DB_DDL:update}


# hosts clients
erp_itau.host: ${HOST_ERP_ITAU:`http://localhost:9091`}
bcb.host: ${HOST_BCB:`http://localhost:8082`}