micronaut:
  application:
    name: keyManagerGrpc

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5435/km_grpc_pix`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    dialect: ${DB_DIALECT:POSTGRES}
jpa.default.properties.hibernate.hbm2ddl.auto: ${DB_DDL:update}


# hosts clients
kmgrpc:
  hosts:
    erp_itau: ${HOST_ERP_ITAU:`http://localhost:9091`}